services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    env_file: .env
    restart: always
    ports:
      - "3000:3000"

    # захист і лог-ротація
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    volumes:
      - .:/app

    entrypoint: /entrypoint.sh

  studio_pangeya_nginx:
    image: nginx:1.19
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
